
[theme]
primaryColor = "#12BDF2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#1E293B"

[server]
headless = true
port = 5000
address = "0.0.0.0"

[browser]
gatherUsageStats = false
